#!/bin/sh

# Replace environment variables in JS files
echo "Replacing environment variables in JS files..."

for file in /usr/share/nginx/html/assets/index.*.js; do
  echo "Processing $file ..."

  sed -i "s|VITE_ADMIN_SERVICE_PLACEHOLDER|${VITE_ADMIN_SERVICE}|g" $file
  sed -i "s|VITE_WORKFLOW_SERVICE_PLACEHOLDER|${VITE_WORKFLOW_SERVICE}|g" $file
  sed -i "s|VITE_RCMS_SERVICE_PLACEHOLDER|${VITE_RCMS_SERVICE}|g" $file
  sed -i "s|VITE_FPS_SERVICE_PLACEHOLDER|${VITE_FPS_SERVICE}|g" $file
  sed -i "s|VITE_UPLOAD_SERVICE_PLACEHOLDER|${VITE_UPLOAD_SERVICE}|g" $file
  sed -i "s|VITE_API_BASE_RATION_CARD_PERSONAL_DETAILS_SERVICE_PLACEHOLDER|${VITE_API_BASE_RATION_CARD_PERSONAL_DETAILS_SERVICE}|g" $file
  sed -i "s|VITE_API_BASE_RATION_CARD_OTHERS_SERVICE_PLACEHOLDER|${VITE_API_BASE_RATION_CARD_OTHERS_SERVICE}|g" $file
  sed -i "s|VITE_API_BASE_RATION_CARD_ADDRESS_SERVICE_PLACEHOLDER|${VITE_API_BASE_RATION_CARD_ADDRESS_SERVICE}|g" $file
  sed -i "s|VITE_API_BASE_MASTER_MANAGEMENT_STATE_SERVICE_PLACEHOLDER|${VITE_API_BASE_MASTER_MANAGEMENT_STATE_SERVICE}|g" $file
  sed -i "s|VITE_API_SERVICES_PLACEHOLDER|${VITE_API_SERVICES}|g" $file
  sed -i "s|VITE_API_VERSION_PLACEHOLDER|${VITE_API_VERSION}|g" $file
  sed -i "s|VITE_CURRENT_SELECTED_LGD_PLACEHOLDER|${VITE_CURRENT_SELECTED_LGD}|g" $file
  sed -i "s|VITE_API_SELECTED_LANGUAGE_PLACEHOLDER|${VITE_API_SELECTED_LANGUAGE}|g" $file
done

echo "Starting NGINX..."
exec "$@"
